import { describe, it, expect, vi, beforeEach } from "vitest";
import { getCachedImages } from "../cache";

// Mock database
const mockDb = {
  select: vi.fn(),
};

vi.mock("@/lib/db", () => ({
  getDb: vi.fn(() => Promise.resolve(mockDb)),
}));

describe("getCachedImages", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    // Setup chainable mock
    const mockChain = {
      from: vi.fn().mockReturnThis(),
      where: vi.fn().mockReturnThis(),
      orderBy: vi.fn().mockReturnThis(),
      limit: vi.fn().mockReturnThis(),
      offset: vi.fn().mockReturnThis(),
      then: vi.fn((resolve) => resolve([])), // For await
    };
    mockDb.select.mockReturnValue(mockChain);
  });

  it("should fetch images with default parameters", async () => {
    const mockImages = [{ id: 1, url: "test.jpg" }];
    const mockCount = [{ count: 1 }];

    // Mock data query
    const mockDataChain = {
      from: vi.fn().mockReturnThis(),
      where: vi.fn().mockReturnThis(),
      orderBy: vi.fn().mockReturnThis(),
      limit: vi.fn().mockReturnThis(),
      offset: vi.fn().mockResolvedValue(mockImages),
    };

    // Mock count query
    const mockCountChain = {
      from: vi.fn().mockReturnThis(),
      where: vi.fn().mockResolvedValue(mockCount),
    };

    mockDb.select
      .mockReturnValueOnce(mockDataChain) // First call is data query
      .mockReturnValueOnce(mockCountChain); // Second call is count query

    const result = await getCachedImages();

    expect(result.images).toEqual(mockImages);
    expect(result.total).toBe(1);
    expect(mockDb.select).toHaveBeenCalledTimes(2);
  });

  it("should apply category filter", async () => {
    await getCachedImages("cakes");
    // We can't easily check the exact SQL generated by drizzle-orm mocks,
    // but we can verify the chain was called.
    expect(mockDb.select).toHaveBeenCalled();
  });

  it("should apply bucket filter", async () => {
    await getCachedImages(undefined, undefined, 50, 0, "news");
    expect(mockDb.select).toHaveBeenCalled();
  });

  it("should apply tag filter", async () => {
    await getCachedImages(undefined, "birthday");
    expect(mockDb.select).toHaveBeenCalled();
  });
});
